export const actionTypes = {
  SET_TRENDING_CONTENT: "SET_TRENDING_CONTENT",
  SET_SEARCH_CONTENT: "SET_SEARCH_CONTENT",
  SET_AIRING_CONTENT: "SET_AIRING_CONTENT",
  SET_UPCOMING_CONTENT: "SET_UPCOMING_CONTENT",
};

export type AppAction = {
  type: any;
  payload: any;
};
